CREATE TABLE wire_gauge_references(
wire_gauge	DECIMAL(10)	NULL
,color_id	NVARCHAR(100)	NULL
,jaso_lower_limit	DECIMAL(20)	NULL
,jaso_upper_limit	DECIMAL(20)	NULL
,iso_lower_limit	DECIMAL(20)	NULL
,iso_upper_limit	DECIMAL(20)	NULL
,updated_by	INT	NULL
,updated_date	DATE	NULL)